'use strict';
const $ = id => document.getElementById(id);
const invoke = (command,args) => window.__TAURI__.core.invoke(command,args);
$('quit-app').onclick=()=>action(()=>invoke('quit_app',{}));
let snapshot, busy = false;
const legacy=document.createElement('article');legacy.className='wide';legacy.innerHTML='<h2>可选 · 检测已有源码安装</h2><p>填写已有 PLA 源码目录，仅检查安装布局与配置文件是否存在，不读取或导入密钥，不接管已有服务。</p><label>现有 PLA 目录<input id="legacy-root" placeholder="D:\\AI_Tools\\plus-local-agent"></label><button id="detect-legacy">检查已有安装</button>';$('setup').prepend(legacy);
$('detect-legacy').onclick=()=>action(async()=>{const result=await rpc('detect_legacy',{path:$('legacy-root').value.trim()});notice(result.recognized_source_install?'已识别 PLA 源码安装。配置和服务保持独立，不会自动导入或接管。':'未识别 PLA 源码安装；该目录未被修改。');});
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';}
function friendlyError(error){const text=String(error);return ({'Stop services before changing configuration':'请先停止服务，再保存连接或浏览器配置。','Start Runtime before connecting Tunnel':'请先启动 Runtime，再连接 Tunnel。','Configure this machine\'s Tunnel ID and runtime API key':'请填写并保存 Tunnel ID 和 Runtime API key，再连接 Tunnel。','Stop Runtime before changing workspace permissions':'请先停止 Runtime，再保存工作区授权。','Runtime is stopped':'请先启动 Runtime，再运行本地工具验证。'})[text]||text;}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(friendlyError(e),true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function rpc(command,args={}){return invoke('manage',{command,args});}
function view(name){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('hidden',el.id!==name));document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('selected',el.dataset.view===name));$('heading').textContent=({overview:'运行概览',setup:'首次配置与连接',workspaces:'授权工作区',logs:'日志与诊断',about:'版本与维护'})[name];}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
document.querySelectorAll('[data-link]').forEach(b=>b.addEventListener('click',()=>action(()=>invoke('official_link',{topic:b.dataset.link}))));
async function refresh(){snapshot=await rpc('status');const c=snapshot.config;$('version').textContent=c.version;$('runtime').textContent=({ready:'MCP 已就绪',starting:'启动中',stopped:'已停止'})[snapshot.runtime];$('tunnel').textContent=({ready:'Tunnel 已就绪',stopped:'已停止',exited:'异常退出',starting_or_disconnected:'启动中或未连接'})[snapshot.tunnel];$('verified').textContent=snapshot.local_mcp_verified?'本地调用通过':'未验证';$('browser').textContent=snapshot.browser;$('optional').textContent=`Office: ${snapshot.office} / Skills: ${snapshot.skills}`;$('data-directory').textContent=c.data_directory;$('runtime-port').value=c.runtime_port;$('health-port').value=c.health_port;$('tunnel-id').value=c.tunnel_id;$('credential-status').textContent=c.credential_saved?'已保存加密凭据':'尚未保存凭据';$('autostart').checked=c.autostart;renderWorkspaces();}
function renderWorkspaces(){const list=$('workspace-list');list.replaceChildren();const roots=snapshot.workspaces.roots;if(!Object.keys(roots).length){list.textContent='尚未添加额外工作区。PLA 私有默认工作区仍可用于本地验证。';return;}for(const [name,root] of Object.entries(roots)){const row=document.createElement('div');row.className='workspace-row';const details=document.createElement('div');const title=document.createElement('strong');title.textContent=name;const path=document.createElement('p');path.textContent=root.path;const permissions=document.createElement('p');permissions.textContent=`读取 ${root.read?'✓':'–'} · 写入 ${root.write?'✓':'–'} · 受控执行 ${root.execute?'✓':'–'}`;details.append(title,path,permissions);const remove=document.createElement('button');remove.textContent='移除授权';remove.addEventListener('click',()=>action(async()=>{await rpc('workspace_remove',{name,expected_sha256:snapshot.workspaces.config_sha256});await refresh();notice('授权已移除，文件保留。');}));row.append(details,remove);list.append(row);}}
$('refresh').onclick=()=>action(refresh);
$('save-browser').onclick=()=>action(async()=>{await rpc('configure',{browser_enabled:$('browser-enabled').checked,browser_port:Number($('browser-port').value)});await refresh();notice('浏览器偏好已保存。启动 Runtime 后会检查真实 Provider 状态。');});
const refreshBase=refresh;
const tunnelText={ready:'已连接远端服务',stopped:'已停止',exited:'异常退出',starting_or_disconnected:'启动中或未连接',disconnected:'连接失败或中断',local_ready_waiting_control_plane:'本地就绪，远端连接待确认'};
refresh=async()=>{await refreshBase();$('browser-enabled').checked=snapshot.config.browser_enabled;$('browser-port').value=snapshot.config.browser_port;$('browser').textContent=({disabled:'未启用',component_missing:'组件缺失',starting_or_unavailable:'启动中或暂不可用',unavailable:'暂不可用，请查看诊断',edge_missing:'未检测到 Microsoft Edge',provider_ready:'组件已连接，浏览器调用需另行验证'})[snapshot.browser]||'暂不可用';$('optional').textContent='Office：组件未安装 · Skills：组件未安装';if(snapshot.runtime==='exited')$('runtime').textContent='异常退出';if(snapshot.last_error)notice(snapshot.last_error,true);};
function serviceAction(command){return action(async()=>{await rpc(command);await refresh();notice(command==='connect'?'Tunnel 已启动，等待真实连接检测。':'服务操作已完成。');});}
for(const command of ['start','stop','restart','connect'])$(command).onclick=()=>serviceAction(command);
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>serviceAction(button.dataset.command));
$('save-connection').onclick=()=>action(async()=>{await rpc('configure',{runtime_port:Number($('runtime-port').value),health_port:Number($('health-port').value),tunnel_id:$('tunnel-id').value.trim()});const secret=$('secret').value;if(secret){await rpc('credential',{secret});$('secret').value='';}await refresh();notice('连接配置已保存。');});
$('save-workspace').onclick=()=>action(async()=>{await rpc('workspace_save',{name:$('workspace-name').value.trim(),path:$('workspace-path').value.trim(),read:$('allow-read').checked,write:$('allow-write').checked,execute:$('allow-execute').checked,expected_sha256:snapshot.workspaces.config_sha256});await refresh();notice('工作区授权已保存。');});
const refreshWithComponents=refresh;
refresh=async()=>{await refreshWithComponents();$('tunnel').textContent=tunnelText[snapshot.tunnel]||'连接待确认';};
$('verify').onclick=()=>action(async()=>{const result=await rpc('verify');await refresh();notice(`真实本地 MCP 调用：${result.local_mcp}。Tunnel 链路及 ChatGPT 调用需分别验收。`);});
$('complete-setup').onclick=()=>action(async()=>{if(!snapshot.local_mcp_verified)throw '请先完成真实本地工具验证。';await rpc('configure',{onboarding_complete:true});await refresh();view('overview');notice('本地配置向导已完成。服务继续运行，请在 ChatGPT 侧完成授权和端到端验收。');});
$('load-logs').onclick=()=>action(async()=>{$('log-output').textContent=(await rpc('logs')).lines.join('\n')||'暂无日志';});
$('diagnose').onclick=()=>action(async()=>{const report=await rpc('diagnose');$('log-output').textContent=JSON.stringify(report,null,2);notice('诊断报告已保存：'+report.report_path);});
$('autostart').onchange=()=>action(async()=>{try{await invoke('autostart',{enabled:$('autostart').checked});}finally{await refresh();}notice('登录启动偏好已保存。');});
action(async()=>{await refresh();if(!snapshot.config.onboarding_complete)view('setup');});
setInterval(()=>{if(!busy && !$('overview').classList.contains('hidden'))action(refresh);},10000);
